name: VNC with Firefox and Cloudflared

on: [push]

jobs:
  setup-vnc:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tigervnc-standalone-server firefox xterm

      # 3. 配置VNC
      - name: Configure VNC
        run: |
          mkdir -p ~/.vnc
          echo "#!/bin/sh" > ~/.vnc/xstartup
          echo "tigervncserver -xstartup /usr/bin/xterm" >> ~/.vnc/xstartup  # 启动xterm
          echo "firefox &" >> ~/.vnc/xstartup  # 启动firefox
          chmod +x ~/.vnc/xstartup

      # 4. 设置VNC密码
      - name: Set VNC password
        run: |
          echo "password" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      # 5. 启动VNC服务器
      - name: Start VNC server
        run: |
          vncserver :1 -geometry 1280x1024 -depth 24

      # 6. 检查VNC服务器状态
      - name: Check VNC server status
        run: |
          netstat -tuln | grep 5901

      # 7. 安装Cloudflared
      - name: Install Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      # 8. 启动Cloudflared隧道（TCP模式）
      - name: Start Cloudflared tunnel (TCP mode)
        run: |
          cloudflared tunnel --url tcp://localhost:5901 > cloudflared.log 2>&1 &
          sleep 5  # 等待Cloudflared启动
          echo "Cloudflared tunnel started. Check the log for the public URL."

      # 9. 输出Cloudflared日志
      - name: Output Cloudflared log
        run: |
          cat cloudflared.log

      # 10. 保持运行
      - name: Keep running
        run: |
          sleep 3000
